"use client";
import { useEffect,useState } from "react";
import { Brand } from "@/components/Brand";
const TOTAL_TABLES=30;
export default function CustomerServicePage(){
 const [loggedIn,setLoggedIn]=useState(false),[key,setKey]=useState(""),[tables,setTables]=useState([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[loginLoading,setLoginLoading]=useState(false);
 async function load(){try{const res=await fetch("/api/staff/service",{cache:"no-store"});const data=await res.json();if(res.status===401){setLoggedIn(false);setLoading(false);return}if(!res.ok)throw new Error(data.message||"โหลดข้อมูลไม่ได้");const map=new Map((data.sessions||[]).map(s=>[String(s.table_number),s]));setTables(Array.from({length:TOTAL_TABLES},(_,i)=>({number:String(i+1),session:map.get(String(i+1))||null})));setLoggedIn(true)}catch(e){setMessage(e.message||"เกิดข้อผิดพลาด")}finally{setLoading(false)}}
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 async function login(e){e.preventDefault();setLoginLoading(true);setMessage("");try{const res=await fetch("/api/staff/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key})});const data=await res.json();if(!res.ok)throw new Error(data.message||"เข้าสู่ระบบไม่ได้");setKey("");await load()}catch(e){setMessage(e.message||"เข้าสู่ระบบไม่ได้")}finally{setLoginLoading(false)}}
 if(!loggedIn&&!loading)return <main className="container floor-page"><header className="floor-login-brand"><Brand compact/><span>FLOOR MONITOR</span></header><section className="floor-login"><span>PRIVATE STAFF AREA</span><h1>แผนผังโต๊ะ<br/><em>ของหวานหิมะ</em></h1><p>เข้าสู่ระบบเพื่อดูว่าโต๊ะไหนกำลังใช้งาน</p><form onSubmit={login}><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="STAFF ACCESS KEY"/><button disabled={loginLoading}>{loginLoading?"กำลังตรวจ...":"เข้าสู่ระบบ →"}</button></form>{message&&<p className="notice error">{message}</p>}</section></main>;
 if(loading)return <main className="container floor-page loading-page"><Brand compact/><p>กำลังอ่านสถานะโต๊ะ...</p></main>;
 const open=tables.filter(t=>t.session).length;
 return <main className="container floor-page"><header className="floor-header"><div><Brand compact/></div><div><span>FLOOR MONITOR / LIVE</span><h1>แผนผังโต๊ะ</h1></div><div className="floor-count"><strong>{open}</strong><span>OPEN</span></div></header><section className="floor-grid">{tables.map(t=><article className={`floor-table ${t.session?"open":""}`} key={t.number}><span>TABLE</span><strong>{t.number}</strong>{t.session?<p>ผู้ใหญ่ {t.session.adult_count} • เด็ก {t.session.child_count}</p>:<p>ว่าง</p>}<i>{t.session?"กำลังใช้งาน":"พร้อมรับลูกค้า"}</i></article>)}</section><footer>อัปเดตทุก 5 วินาที • หน้าสำหรับพนักงาน</footer></main>;
}
